# **Part 1**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
tenZeros=np.zeros(10)
print(tenZeros)
tenOnes=np.ones(10)
print(tenOnes)
tenFives=np.ones(10)*5
print(tenFives)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]

In [ ]:
x = np.arange(10,50,2) #in range of 10 and 50 with size 2 
print("Even numbers between 10 to 50:")
print(x)

Even numbers between 10 to 50:
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]

In [ ]:
y=np.random.randint(10,50,1)
print(y)

[21]

In [ ]:
a = np.random.rand(3,3)
print("created:",a)
np.savetxt("randomMatrix.txt",a,)
a_load=np.loadtxt("randomMatrix.txt")
print("loaded:",a_load)

created: [[0.04686633 0.79601023 0.83094029]
 [0.40597    0.72247007 0.53692956]
 [0.49562541 0.08051492 0.135648  ]]
loaded: [[0.04686633 0.79601023 0.83094029]
 [0.40597    0.72247007 0.53692956]
 [0.49562541 0.08051492 0.135648  ]]

# **Part 2**

In [ ]:
import matplotlib.image as img
imageMatrix = img.imread('image.jpg')#reading image and storing in the matrix (3d)

#converting from the 3D matrix to 2D matrix
imageMatrix = imageMatrix.reshape(imageMatrix.shape[0],imageMatrix.shape[1]*imageMatrix.shape[2])
print(imageMatrix)

df = pd.DataFrame(imageMatrix)#converting the matrix to data frame
 
df.to_csv('file1.csv',index=False)#saving the dataframe as csv file

[[220 255 251 ... 220 255 251]
 [220 255 251 ... 220 255 251]
 [220 255 251 ... 220 255 251]
 ...
 [220 255 251 ... 220 255 251]
 [220 255 251 ... 220 255 251]
 [220 255 251 ... 220 255 251]]

In [ ]:
len(df)#length of dataframe gives the number of rows 
new_df = pd.read_csv('file1.csv',nrows=len(df)-1,usecols=range(len(df.columns)-1))
print(new_df)

       0    1    2    3    4    5    6  ...  667  668  669  670  671  672  673
0    220  255  251  220  255  251  220  ...  255  251  220  255  251  220  255
1    220  255  251  220  255  251  220  ...  255  251  220  255  251  220  255
2    220  255  251  220  255  251  220  ...  255  251  220  255  251  220  255
3    220  255  251  220  255  251  220  ...  255  251  220  255  251  220  255
4    220  255  251  220  255  251  220  ...  255  251  220  255  251  220  255
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
219  220  255  251  220  255  251  220  ...  255  251  220  255  251  220  255
220  220  255  251  220  255  251  220  ...  255  251  220  255  251  220  255
221  220  255  251  220  255  251  220  ...  255  251  220  255  251  220  255
222  220  255  251  220  255  251  220  ...  255  251  220  255  251  220  255
223  220  255  251  220  255  251  220  ...  255  251  220  255  251  220  255

[224 rows x 674 columns]

In [ ]:
from datetime import date
now = pd.to_datetime(str(date.today()), format='%Y-%m-%d')
print("Today date:",now)

Today date: 2021-08-10 00:00:00

# **Part 3**

In [ ]:
def birth_age(age):
  today=date.today()
  age=today.year - age.year - ((today.month, today.day) <(age.month, age.day)) 
  return age
print("enter you birth date:")         
year=int(input("year: "))
month=int(input("month: "))
day=int(input("day: "))
age=birth_age((date(year,month,day)))
print(age,"years")

enter you birth date:
year: 2002
month: 08
day: 10
19 years